# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('profile', models.CharField(max_length=256)),
                ('ipaddress', models.GenericIPAddressField()),
                ('useragent', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('likecount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('profile', models.CharField(max_length=256)),
                ('ipaddress', models.GenericIPAddressField()),
                ('useragent', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('viewcount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Topic'),
        ),
    ]
