# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160529_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='profile',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='topic',
            name='profile',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
